### ISSUE TITLE
Use grease pencil to define topology hints

### ISSUE THREAD

**Issue by dradix** [cgvirus/Blender-Instant-Mesh-Bridge-addon#1]
Hello, I'd like to know if you have planned to update this to use the grease pencil to draw hints for the topology like in the Instant mesh app but directly inside of Blender.  Also, what is the license of this? Can I use it as a base code to try to implement this feature?

**Comment by cgvirus** [comment]
Hello, No i have no plan for it. As it's blender addon, it's following the license of Blender (GPL). Sure, if you want to implement it you are free to do so. Please let me know if possible. I am interested. Thanks.
