### ISSUE TITLE
traceback error

### ISSUE THREAD

**Issue by peachpie87** [cgvirus/Blender-Instant-Mesh-Bridge-addon#2]
I installed the addon as specified in the tutorial. when I tried to use the addon in blender 2.82 I got this error message:
[https://imgur.com/sdNxENv](url)
it's saying there is no attribute and location unknown

**Comment by cgvirus** [comment]
Hello, I will need the full error message. Can't reproduce it in 2.82 and 83

**Comment by cgvirus** [comment]
issue closed due to unclear report and inactivity. Please feel free to reopen the issue if not resolved by the new package update. Thanks.
