### ISSUE TITLE
Can't install in Blender 2.90

### ISSUE THREAD

**Issue by v9999** [cgvirus/Blender-Instant-Mesh-Bridge-addon#3]
Hello,

When I try to install the addon, I get this message and it won't install:

`bpy.context.space_data.system_bookmarks_active = 3
Modules Installed () from 'C:\\Users\\xxx\\Downloads\\InstantMeshesBridge.zip' into 'C:\\Users\\xxx\\AppData\\Roaming\\Blender Foundation\\Blender\\2.90\\scripts\\addons'
`

**Comment by frustaci** [comment]
Rename the installed script in its folder from InstantMeshesBridge.py to `__init__.py` or just copy the InstantMeshesBridge.py manually without folder to \scripts\addons folder.
Blender requires all scripts in folders to start from a `__init__.py` file now.

**Comment by cgvirus** [comment]
Package updated. Please feel free to open the issue again if not solved. Thanks.
