### ISSUE TITLE
Unable to define path to Instant Meshes Executable on Windows

### ISSUE THREAD

**Issue by acidragn** [cgvirus/Blender-Instant-Mesh-Bridge-addon#6]
On windows, the Preferences is missing the path field for the Instant Meshes executable.
![image](https://user-images.githubusercontent.com/102005359/233402927-59fc7456-8a57-4078-9f1e-ab13d1fa8800.png)
...and obviously it then fails to open Instant Meshes.
![image](https://user-images.githubusercontent.com/102005359/233402421-6ec25b93-7b7d-40b1-8f90-694122764ce5.png)

**Comment by cgvirus** [comment]
Hello, 
- please remove the previous install.
- Rather than extracting the zip, install the whole downloaded zip file directly instead.

Blender API has been changed after 2.8 and now we don't need to extract the zip anymore.

Let me know if it solves the issue.
Thanks.

**Comment by acidragn** [comment]
That did the trick. Thank you very much!

**Comment by cgvirus** [comment]
Most Welcome
