### ISSUE TITLE
Blender 4 bridge errors

### ISSUE THREAD

**Issue by zerodean** [cgvirus/Blender-Instant-Mesh-Bridge-addon#8]
Will not link/execute to EXE during bridge operation due to errors in Blender 4.

**Comment by iddqd4life** [comment]
> Will not link/execute to EXE during bridge operation due to errors in Blender 4.

Install a zip file, not a .py file.

**Comment by cgvirus** [comment]
Hi can you try from the updated release?

Download the zip file from releases: https://github.com/cgvirus/Blender-Instant-Mesh-Bridge-addon/releases
Remove old addon(if any) and restart blender
Frome Blender addon preference install the zip.
in addon preference point the instant meshes executable path.
select the object and in Blender object menu>instant meshes remesh

**Comment by zerodean** [comment]
The new update appears to have fixed it for me. **Thank you!**

**Comment by cgvirus** [comment]
solved
