### ISSUE TITLE
Blender 4 error

### ISSUE THREAD

**Issue by cheboot** [cgvirus/Blender-Instant-Mesh-Bridge-addon#9]
```
Python: Traceback (most recent call last):
  File "C:\Users\sevan\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\Blender-Instant-Mesh-Bridge-addon-master\Instant_Meshes_Remesh.py", line 116, in execute
    bpy.ops.export_scene.obj(filepath=orig,
  File "C:\Program Files\Blender Foundation\Blender 4.0\4.0\scripts\modules\bpy\ops.py", line 109, in __call__
    ret = _op_call(self.idname_py(), kw)
AttributeError: Calling operator "bpy.ops.export_scene.obj" error, could not be found
```
Happens when try to remesh

**Comment by cgvirus** [comment]
Hi can you try from the updated release?

Download the zip file from releases: https://github.com/cgvirus/Blender-Instant-Mesh-Bridge-addon/releases
Remove old addon(if any) and restart blender
Frome Blender addon preference install the zip.
in addon preference point the instant meshes executable path.
select the object and in Blender object menu>instant meshes remesh

**Comment by cgvirus** [comment]
closed as solved and no response. Feel free to reopen if needed.
